name: Push MD Files to Another Repository

on:
  push:
    branches:
      - main

jobs:
  push-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone target repository
        run: git clone https://github.com/matze2402/myyyy.git myyyy
        # Replace 'yourusername' with your GitHub username and 'myyyy' with the name of your target repository

      - name: Copy .md files to target repository
        run: |
          mkdir -p myyyy/fin
          cp Testpurpose/*.md myyyy/fin/

      - name: Commit and push .md files to target repository
        run: |
          cd myyyy
          git config --local user.email "action@github.com"
          git config --local user.name "yourusername"
          git add .
          git commit -m "Add .md files from source repository"
          git push
