name: Move New Markdown Files

on:
  push:
    branches:
      - main  # Change this to your main branch name if needed
    paths:
      - 'pages/Testpurpose/*.md'  # Specify the path to monitor for changes

jobs:
  move_markdown_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Move New Markdown Files
        run: |
          mkdir -p temp_folder  # Create the temp_folder if it doesn't exist
          for file in ./pages/Testpurpose/*.md ; do
            if [[ -e $file ]]; then
              mv "$file" temp_folder/
            fi
          done
          
      - name: Check if Files Moved
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.email "you@example.com"  # Configure git user email
            git config --global user.name "matze2402"  # Configure git user name
            git config --global url.https://${{ secrets.admin }}@github.com/.insteadOf https://github.com/ 
            git add .
            git commit -m "Moved new Markdown files from pages folder to temp_folder/"
            git push origin main  # Push changes to the main branch
          fi
