name: Move New Markdown Files

on:
  push:
    branches:
      - main  # Change this to your main branch name if needed
    paths:
      - 'pages/Testpurpose/*.md'  # Specify the path to monitor for changes

jobs:
  move_markdown_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: List New Markdown Files
        id: list_new_md_files
        run: |
          mkdir -p temp_folder  # Create the temp_folder if it doesn't exist
          git diff --name-only --diff-filter=A origin/main ./pages/Testpurpose/*.md > new_md_files.txt
          echo "::set-output name=new_md_files::$(cat new_md_files.txt)"
      
      - name: Move New Markdown Files
        run: |
          while IFS= read -r file; do
            mkdir -p "temp_folder/$(dirname "$file")"
            mv "$file" "temp_folder/$file"
          done < new_md_files.txt
          git config --global user.email "you@example.com"  # Configure git user email
          git config --global user.name "Matze2402"  # Configure git user name
          git config --global url.https://${{ secrets.admin }}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Moved new Markdown files from source folder to temp_folder/"
          git push origin main  # Push changes to the main branch
