name: Move New Markdown Files

on:
  push:
    branches:
      - main  # Change this to your main branch name if needed
    #paths:
      #- 'pages/Testpurpose/*.md'  # Specify the path to monitor for changes

jobs:
  copy_markdown_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create New Folder
        run: mkdir -p copied_md_files  # Create the new folder if it doesn't exist

      
