name: Copy Files

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new folder
        run: mkdir -p destination_folder

      - name: Copy files to new folder
        run: |
          find Testpurpose -type f -name "*.md" -exec cp {} destination_folder/ \;
