name: Push MD Files to Another Repository

on:
  push:
    branches:
      - main
    paths:
    - 'Testpurpose/*.md'

jobs:
  push-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone target repository
        run: git clone https://github.com/matze2402/myyyy.git myyyy
        # Replace 'yourusername' with your GitHub username and 'myyyy' with the name of your target repository

      - name: Copy .md files to target repository
        run: |
          mkdir -p myyyy/fin
          cp Testpurpose/*.md myyyy/fin/

      - name: Commit and push .md files to target repository
        run: |
          cd myyyy
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"
          git config --global url.https://${{ secrets.admin}}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Add .md files from source repository"
          git push

      - name: Dispatch trigger for pushing
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ADMIN }}
          repository: Matze2402/temp_repo
          event-type: push-md   
