name: Copy Files

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Copy files
      run: |
        mkdir -p destination_folder  # Create destination folder if not exists
        cp -r ./pages/Testpurpose/. destination_folder/
