name: Move New Markdown Files

on:
  push:
    branches:
      - main  # Change this to your main branch name if needed
    paths:
      - 'pages/Testpurpose/*.md'  # Specify the path to monitor for changes

jobs:
  copy_markdown_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create New Folder
        run: mkdir -p copied_md_files  # Create the new folder if it doesn't exist

      - name: Copy New Markdown Files
        run: |
          for file in $(git diff --name-only --diff-filter=A origin/main pages/Testpurpose/*.md); do
            cp "$file" copied_md_files/
          done

      - name: Check if Files Copied
        run: |
          if [[ -n $(ls copied_md_files/*.md 2>/dev/null) ]]; then
            git config --global user.email "you@example.com"  # Configure git user email
            git config --global user.name "Your Name"  # Configure git user name
            git config --global url.https://${{ secrets.admin }}@github.com/.insteadOf https://github.com/
            git add copied_md_files/
            git commit -m "Copied new Markdown files to copied_md_files/"
            git push origin main  # Push changes to the main branch
          fi
